#!/bin/sh
# $Id: mk,v 1.7 2015-10-23 18:17:18-07 - - $

cat >test1.in <<__END__
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
tttttttttttttttttttttttttttttttttttttttt
aaaaaaaaaaaaaaaaaaaa
oooooooooooooooooooo
__END__

cat >test2.in <<__END__
eeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeee eeeeeeeeee
eeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeee eeeeeeeeee
tttttttttttttttttttt tttttttttttttttttttt
aaaaaaaaaaaaaaaaaaaa
oooooooooooooooooooo
iiiiiiiiii
nnnnn
sssss
h
r
__END__

cid $0 phuffman.perl
phuffman.perl <test1.in >test1.out 2>&1
phuffman.perl <test2.in >test2.out 2>&1
more test1.in test1.out test2.in test2.out >tests.lis </dev/null
mkpspdf Listing.ps tests.lis $0 phuffman.perl
